name: aplikasi_flutter_pemula
description: Aplikasi Flutter Pemula Dicoding
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <=3.3.8'

dependencies:
  fluttertoast: ^8.2.1
  go_router: ^6.5.7
  http: ^0.13.5
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
